name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
   branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    # - name: Build
    #   run: npm run build:prod

    # - name: Deploy
    #   if: success()
    #   uses: PaulHinterberger/test_github_actions@main
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: dist/angular-github-test
    #     enable_jekyll: true